version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14  # Use the desired Node.js version
    steps:
      - checkout
      - run: npm install
      - run: npm run test:ui
      - run: npm run test:api

workflows:
  version: 2
  test:
    jobs:
      - test
