version: 2.1

jobs:
  run-ui-tests:
    docker:
      - image: circleci/node:16-browsers  # Update to a version that supports newer syntax
    steps:
      - checkout
      - run:
          name: Check Node Version  # Step to confirm Node version
          command: node -v
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run UI Tests
          command: npm run test:ui

  run-api-tests:
    docker:
      - image: circleci/node:16-browsers  # Update to a version that supports newer syntax
    steps:
      - checkout
      - run:
          name: Check Node Version  # Step to confirm Node version
          command: node -v
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run API Tests
          command: npm run test:api

workflows:
  version: 2
  test:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests
