version: 2.1

jobs:
  run-ui-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run UI Tests
          command: npm test -- --testPathPattern=ui-tests

  run-api-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run API Tests
          command: npm test -- --testPathPattern=api-tests

workflows:
  version: 2
  test:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests
