version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16  # Use Node.js version 16

jobs:
  run-ui-tests:
    docker:
      - image: circleci/node:16  # Test with Node.js version 16
    steps:
      - checkout
      - run:
          name: Install Google Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run UI Tests
          command: npm run test:ui

  
  run-api-tests:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start Server
          command: npm run start &
      - run:
          name: Wait for Server to be Ready
          command: wait-on http://localhost:3000  # Adjust the URL based on your server
      - run:
          name: Run API Tests
          command: npm run test:api