version: 2.1

jobs:
  run-ui-tests:
    docker:
      - image: circleci/node:16  # Test with Node.js version 16
    steps:
      - checkout
      - run:
          name: Install Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run UI Tests
          command: npm run test:ui

  run-api-tests:
    docker:
      - image: circleci/node:16  # Test with Node.js version 16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run API Tests
          command: npm run test:api

workflows:
  version: 2
  test:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests
